### ISSUE TITLE
Fabric version?

### ISSUE THREAD

**Issue by Soufre** [Gibatron/attraction#1]
Great mod, just wondering if you're planning on making a Fabric version since I really, really love the concept of this mod by the looks of it.

**Comment by noWickedfortheRest** [comment]
Maybe when I'm less busy with some of my current projects. Although it does use Quilt's REAs and I'm not sure if that could be easily converted over.

**Comment by Soufre** [comment]
Understandable, I hope everything turns out well. Keep the great work goin'!
