### ISSUE TITLE
Gravity API Support

### ISSUE THREAD

**Issue by FractalGeodes** [Gibatron/attraction#2]
~~Firstly a mod this fun to mess around with is illegal~~

Secondly, I tried it out using [Gravity API](https://modrinth.com/mod/gravity-api) and the results were.. somewhat disappointing.
I flipped upside down and when I went to be magnetized by a block floating in the air it instead pushed me towards the ground

I believe that the calculations for the magnetism are made with the assumption that the entity is right-side up, which at that point isn't the case. I'm not sure how difficult making it work with the gravity changes would be, but my guess is it would just be checking if the player is rotated differently and then changing the velocity based on that.

It's not the biggest deal but we'd really appreciate it if this is fixed so that we have more stuff to get distracted by while making our modpack :catstare:

**Comment by noWickedfortheRest** [comment]
From the sounds of it I don't think it would be too hard to add support, I'll look into it.
