### ISSUE TITLE
Config to change the strength of the magnets

### ISSUE THREAD

**Issue by Fnige** [Gibatron/attraction#3]
Nice mod you got here (I think what the ringlings said explains our thoughts on it best), though one thing we would like to personally see is the ability to change the strength of the lodestones and netherite magnets

**Comment by noWickedfortheRest** [comment]
Modifying the strengths of the blocks can be done through a datapack by modifying `data/attraction/attachments/minecraft/block/magnetic_block.json`
The netherite block has a default value of 9.0 using this method [here](https://github.com/Gibatron/attraction/blob/1.19/src/main/resources/data/attraction/attachments/minecraft/block/magnetic_block.json)
